### PR TITLE
Fixes 498

### LINKED ISSUE #498: Bug: testutil package unexpected results for Histograms
@beorn7 this follows up from our chat in #497 

I'm seeing similar behaviour as reported in #494 with Counters. This time with Histograms. I've written the following failing test

```go
func TestCollectAndCompareHistogram(t *testing.T) {
	inputs := []struct {
		name        string
		c           prometheus.Collector
		metadata    string
		expect      string
		observation float64
	}{
		{
			name: "Testing Histogram Collector",
			c: prometheus.NewHistogram(prometheus.HistogramOpts{
				Name:    "some_histogram",
				Help:    "An example of a histogram",
				Buckets: []float64{1, 2, 3},
			}),
			metadata: `
				# HELP some_histogram An example of a histogram
				# TYPE some_histogram histogram
			`,
			expect: `
				some_histogram{le="1"} 0
				some_histogram{le="2"} 0
				some_histogram{le="3"} 1
        			some_histogram_bucket{le="+Inf"} 1
        			some_histogram_sum 2.5
        			some_histogram_count 1

			`,
			observation: 2.5,
		},
		{
			name: "Testing HistogramVec Collector",
			c: prometheus.NewHistogramVec(prometheus.HistogramOpts{
				Name:    "some_histogram",
				Help:    "An example of a histogram",
				Buckets: []float64{1, 2, 3},
			}, []string{"test"}),

			metadata: `
				# HELP some_histogram An example of a histogram
				# TYPE some_histogram histogram
			`,
			expect: `
				some_histogram{le="1"} 0
				some_histogram{le="2"} 0
				some_histogram{le="3"} 1
        			some_histogram_bucket{le="+Inf"} 1
        			some_histogram_sum 2.5
        			some_histogram_count 1
		
			`,
			observation: 2.5,
		},
	}

	for _, input := range inputs {
		switch collector := input.c.(type) {
		case prometheus.Histogram:
			collector.Observe(input.observation)
		case *prometheus.HistogramVec:
			collector.WithLabelValues("test").Observe(input.observation)
		default:
			t.Fatalf("unsuported collector tested")

		}

		t.Run(input.name, func(t *testing.T) {
			if err := CollectAndCompare(input.c, strings.NewReader(input.metadata+input.expect)); err != nil {
				t.Errorf("unexpected collecting result:\n%s", err)
			}
		})

	}
}
```
 
It returns the following output:

```bash
FAIL
    --- FAIL: TestCollectAndCompareHistogram/Testing_Histogram_Collector (0.00s)
        testutil_test.go:237: unexpected collecting result:
            
            metric output does not match expectation; want:
            
            # HELP some_histogram An example of a histogram
            # TYPE some_histogram histogram
            some_histogram_bucket{le="1"} 0
            some_histogram_bucket{le="2"} 0
            some_histogram_bucket{le="3"} 1
            some_histogram_bucket{le="+Inf"} 1
            some_histogram_sum 2.5
            some_histogram_count 1
            
            
            got:
            
            # HELP some_histogram An example of a histogram
            # TYPE some_histogram histogram
            some_histogram_bucket{le="1"} 0
            some_histogram_bucket{le="2"} 0
            some_histogram_bucket{le="3"} 1
            some_histogram_bucket{le="+Inf"} 1
            some_histogram_sum 2.5
            some_histogram_count 1
```
Comparing the want and the got strings:
```
name:"some_histogram" help:"An example of a histogram" type:HISTOGRAM metric:<histogram:<sample_count:1 sample_sum:2.5 bucket:<cumulative_count:0 upper_bound:1 > bucket:<cumulative_count:0 upper_bound:2 > bucket:<cumulative_count:1 upper_bound:3 > > > 
name:"some_histogram" help:"An example of a histogram" type:HISTOGRAM metric:<histogram:<sample_count:1 sample_sum:2.5 bucket:<cumulative_count:0 upper_bound:1 > bucket:<cumulative_count:0 upper_bound:2 > bucket:<cumulative_count:1 upper_bound:3 > bucket:<cumulative_count:1 upper_bound:inf > > >
```

### PR DESCRIPTION
**Pull request by PhilipGough**
Fixes #498
@beorn7 is this close to what you had in mind? If not let me know and I can revise.

### CODE REVIEW

File: prometheus/testutil/testutil.go [hunk 1]
```diff
@@ -138,20 +138,13 @@ func GatherAndCompare(g prometheus.Gatherer, expected io.Reader, metricNames ...
...
-	}
-	return nil
+	return compare(got, want)
 }
 
-// notMatchingError encodes both provided slices of metric families into the
-// text format and creates a readable error message from the result.
-func notMatchingError(got, want []*dto.MetricFamily) error {
+// compare encodes both provided slices of metric families into the
+// text format compares their string message and returns an error if they do not match.
```
Comment (beorn7) [inline prometheus/testutil/testutil.go]: Nit: commas after "format" and "message".

File: prometheus/testutil/testutil.go [hunk 2]
```diff
@@ -138,20 +138,13 @@ func GatherAndCompare(g prometheus.Gatherer, expected io.Reader, metricNames ...
...
+// In case of error, prints a readable error message from the result.
```
Comment (beorn7) [inline prometheus/testutil/testutil.go]: This sounds like it would call `fmt.Println` or something. Perhaps just mention that the returned error will contain the encoded text of both, got and want.

**Comment by PhilipGough** [comment]
@beorn7 thanks, amended!

**Comment by beorn7** [comment]
Thanks, too. Merging now...
