### PR TITLE
Make the Go 1.17 collector thread-safe

### LINKED ISSUE #968: v1.12.0 race condition
After upgrading to: github.com/prometheus/client_golang v1.12.0
I am getting "**WARNING: DATA RACE**" while testing:
https://github.com/nexmoinc/gosrvlib/tree/main/pkg/metrics/prometheus

The race conditions do not appear in version 1.11.0 or any other previous version.

The race condition do not appear when disabling the t.Parallel() in the unit tests (e.g.: https://github.com/nexmoinc/gosrvlib/blob/main/pkg/metrics/prometheus/client_test.go#L153).

The relevant errors are:
 ```
==================
WARNING: DATA RACE
Read at 0x00c000598660 by goroutine 59:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/map_faststr.go:107 +0x0
  runtime/metrics.runtime_readMetrics()
      /usr/local/go/src/runtime/metrics.go:563 +0xb9
  github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/registry.go:446 +0x133

Previous write at 0x00c000598660 by goroutine 70:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  runtime.initMetrics()
      /usr/local/go/src/runtime/metrics.go:67 +0x1c6
  github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/registry.go:446 +0x133

Goroutine 59 (running) created at:
  github.com/prometheus/client_golang/prometheus.(*Registry).Gather()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/registry.go:538 +0x1137
  github.com/prometheus/client_golang/prometheus/testutil.GatherAndCount()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/testutil/testutil.go:139 +0x7a
  github.com/nexmoinc/gosrvlib/pkg/metrics/prometheus.TestIncLogLevelCounter()
      /home/user/go/src/github.com/nexmoinc/gosrvlib/pkg/metrics/prometheus/client_test.go:144 +0x157
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47

Goroutine 70 (finished) created at:
  github.com/prometheus/client_golang/prometheus.(*Registry).Gather()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/registry.go:538 +0x1137
  github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/http.go:126 +0x11a
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:40 +0x118
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:117 +0xe2
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  net/http.Handler.ServeHTTP-fm()
      /usr/local/go/src/net/http/server.go:87 +0x75
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:204 +0xb3
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:239 +0xec
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:117 +0xe2
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:84 +0xca
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1()
      /home/user/go/pkg/mod/github.com/prometheus/client_golang@v1.12.0/prometheus/promhttp/instrument_server.go:40 +0x118
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2047 +0x4d
  github.com/nexmoinc/gosrvlib/pkg/metrics/prometheus.TestInstrumentHandler()
      /home/user/go/src/github.com/nexmoinc/gosrvlib/pkg/metrics/prometheus/client_test.go:89 +0x3a1
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
=== CONT  TestInstrumentDB
    testing.go:1152: race detected during execution of test
--- FAIL: TestInstrumentDB (0.03s)
=== CONT  TestIncLogLevelCounter
    testing.go:1152: race detected during execution of test
--- FAIL: TestIncLogLevelCounter (0.04s)
=== CONT  TestInstrumentRoundTripper
    testing.go:1152: race detected during execution of test
--- FAIL: TestInstrumentRoundTripper (0.06s)
=== CONT  TestInstrumentHandler
    testing.go:1152: race detected during execution of test
--- FAIL: TestInstrumentHandler (0.07s)
FAIL
```

### PR DESCRIPTION
**Pull request by mknyszek**
Currently the Go 1.17 collector does not protect access to rmSampleBuf,
and Collect may be invoked concurrently. This change adds a mutex around
all uses of rmSampleBuf and pulls out operations that may block on
channels, so concurrent calls to Collect can at least pipeline those two
operations.

Fixes #968

### CODE REVIEW

**Comment by mknyszek** [comment]
CC @kakkoyun @bwplotka

**Review by kakkoyun — APPROVED** [review]
LGTM. Thanks for taking care of it quickly.

You just need to handle DCO and we're good here.

**Comment by mknyszek** [comment]
> LGTM. Thanks for taking care of it quickly.
> 
> You just need to handle DCO and we're good here.

No problem, and the DCO should be resolved.

File: prometheus/go_collector_go117_test.go [hunk 1]
```diff
@@ -280,3 +280,25 @@ func TestExpectedRuntimeMetrics(t *testing.T) {
...
+
+	// Set up multiple goroutines to Collect from the
+	// same GoCollector. In race mode with GOMAXPROCS > 1,
+	// this test should fail often if Collect is not
+	// concurrent-safe.
+	for i := 0; i < 4; i++ {
+		go func() {
+			ch := make(chan Metric)
+			go func() {
+				// Drain all metrics recieved until the
```
Comment (nicolaasuni) [inline prometheus/go_collector_go117_test.go:295]: "recieved" > "received"

**Review by nicolaasuni — COMMENTED** [review]
Typo on a comment.

**Review by bwplotka — COMMENTED** [review]
Thanks!

File: prometheus/go_collector_go117.go [hunk 2]
```diff
@@ -146,22 +157,29 @@ func (c *goCollector) Collect(ch chan<- Metric) {
...
 	var ms runtime.MemStats
 	memStatsFromRM(&ms, c.rmSampleMap)
+
+	c.rmSampleMu.Unlock()
+
+	// Export all the metrics to ch.
+	// At this point we must not access rmSampleBuf or rmSampleMap, because
+	// a concurrent caller could use it. It's safe to Collect all our Metrics,
+	// however, because they're updated in a thread-safe way while MemStats
+	// is local to this call of Collect.
```
Comment (beorn7) [inline prometheus/go_collector_go117.go:179]: Hmm, I guess it's concurrency-safe as in "there are no low-level data races" but elements of `rmMetrics` are still updated (in lines 161, 163) so with a concurrent call to `Collect`, we might collect here a mix of metrics from different `metrics.Read` calls. Perhaps that's fine, but I very much doubt it.

Comment (mknyszek) [reply prometheus/go_collector_go117.go:179]: One thing that comes to mind is that at a given point in time, metrics that would otherwise be consistent with one another may no longer be. In most cases this is harmless, but I did also go out of my way to ensure that the memory metrics in `runtime/metrics` are kept consistent without a STW, so perhaps we should try to maintain that here. 😅 

Good catch. I'm inclined to fix this unless there are any objections.

Comment (kakkoyun) [reply prometheus/go_collector_go117.go:179]: Please go ahead. Thanks @beorn7 for catching it and thanks @mknyszek for quick action.

Comment (mknyszek) [reply prometheus/go_collector_go117.go:179]: Sent #975.

File: prometheus/go_collector_go117_test.go (hunk 1 above)
Comment (mknyszek) [reply prometheus/go_collector_go117_test.go:295]: Sent #975.
